version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing app dependencies...
      - npm install
  build:
    commands:
      - echo Building static site...
      - npm build
  artifacts:
    type: zip
    paths:
      - './build/**/*'
  cache:
    paths:
      - './node_modules/**/*'