version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  base-directory: build
  files:
    - '**/*'
cache:
  paths:
    - './node_modules/**/*'