import { 
    //Center
    bela_vista_polygon, 
    consolacao_polygon, 
    liberdade_polygon, 
    santa_cecilia_polygon,
    republica_polygon,
    cambuci_polygon,
    bom_retiro_polygon,
    se_polygon,
    barra_funda_polygon,
    // North
    santana_polygon,
    vila_guilherme_polygon,
    vila_maria_polygon,
    casa_verde_polygon,
    limao_polygon,
    freguesia_do_o_polygon,
    pirituba_polygon,
    sao_domingos_polygon,
    vila_medeiros_polygon,
    tucuruvi_polygon,
    mandaqui_polygon,
    cachoerinha_polygon,
    brasilandia_polygon,
    jaragua_polygon,
    tremembe_polygon,
    // East
    pari_polygon,
    bras_polygon,
    belem_polygon,
    mooca_polygon,
    tatuape_polygon,
    agua_rasa_polygon,
    vila_prudente_polygon,
    cangaiba_polygon,
    penha_polygon,
    vila_matilde_polygon,
    carrao_polygon,
    vila_formosa_polygon,
    artur_alvim_polygon,
    cidade_lider_polygon,
    sao_mateus_polygon,
    vila_jacui_polygon,
    itaquera_polygon,
    sao_rafael_polygon,
    jose_bonifacio_polygon,
    iguatemi_polygon,
    jardim_helena_polygon,
    vila_curuca_polygon,
    guaianases_polygon,
    cidade_tiradentes_polygon,
    // South
    vila_mariana_polygon,
    ipiranga_polygon,
    saude_polygon,
    sacoma_polygon,
    vila_andrade_polygon,
    santo_amaro_polygon,
    campo_belo_polygon,
    jabaquara_polygon,
    capao_redondo_polygon,
    socorro_polygon,
    cidade_ademar_polygon,
    perdizes_polygon,
    jardim_paulista_polygon,
    // West
    pinheiros_polygon,
    itaim_bibi_polygon,
    lapa_polygon,
    alto_pinheiros_polygon,
    butanta_polygon,
    morumbi_polygon,
    jaguara_polygon,
    vila_leopoldina_polygon,
    jaguare_polygon,
    rio_pequeno_polygon,
    vila_sonia_polygon
  } from '../../maps/sao_paulo_districts'

  
export const dict_polygon_names = {
    // Center
    'bela vista': bela_vista_polygon,
    'consolação': consolacao_polygon,
    'santa cecília': santa_cecilia_polygon,
    'república': republica_polygon,
    'cambuci': cambuci_polygon,
    'liberdade': liberdade_polygon,
    'bom retiro': bom_retiro_polygon,
    'sé': se_polygon,
    // North
    'santana': santana_polygon,
    'vila guilherme': vila_guilherme_polygon,
    'vila maria': vila_maria_polygon,
    'casa verde': casa_verde_polygon,
    'limão': limao_polygon,
    'freguesia do ó': freguesia_do_o_polygon,
    'pirituba': pirituba_polygon,
    'são domingos': sao_domingos_polygon,
    'vila medeiros': vila_medeiros_polygon,
    'tucuruvi': tucuruvi_polygon,
    'mandaqui': mandaqui_polygon,
    'cachoerinha': cachoerinha_polygon,
    'brasilândia': brasilandia_polygon,
    'jaraguá': jaragua_polygon,
    'tremembé': tremembe_polygon,
    // East
    'pari': pari_polygon,
    'brás': bras_polygon,
    'belém': belem_polygon,
    'mooca': mooca_polygon,
    'tatuapé': tatuape_polygon,
    'água rasa': agua_rasa_polygon,
    'vila prudente': vila_prudente_polygon,
    'cangaiba': cangaiba_polygon,
    'penha': penha_polygon,
    'vila matilde': vila_matilde_polygon,
    'carrão': carrao_polygon,
    'vila formosa': vila_formosa_polygon,
    'artur alvim': artur_alvim_polygon,
    'cidade líder': cidade_lider_polygon,
    'são mateus': sao_mateus_polygon,
    'vila jacuí': vila_jacui_polygon,
    'itaquera': itaquera_polygon,
    'são rafael': sao_rafael_polygon,
    'josé bonifácio': jose_bonifacio_polygon,
    'iguatemi': iguatemi_polygon,
    'jardim helena': jardim_helena_polygon,
    'vila curuçá': vila_curuca_polygon,
    'guaianases': guaianases_polygon,
    'cidade tiradentes': cidade_tiradentes_polygon,
    // South
    'vila mariana': vila_mariana_polygon,
    'ipiranga': ipiranga_polygon,
    'saúde': saude_polygon,
    'sacomã': sacoma_polygon,
    'vila andrade': vila_andrade_polygon,
    'santo amaro': santo_amaro_polygon,
    'campo belo': campo_belo_polygon,
    'jabaquara': jabaquara_polygon,
    'capão redondo': capao_redondo_polygon,
    'socorro': socorro_polygon,
    'cidade ademar': cidade_ademar_polygon,
    // West
    'perdizes': perdizes_polygon,
    'barra funda': barra_funda_polygon,
    'jardim paulista': jardim_paulista_polygon,
    'pinheiros': pinheiros_polygon,
    'itaim bibi': itaim_bibi_polygon,
    'lapa': lapa_polygon,
    'alto pinheiros': alto_pinheiros_polygon,
    'butantã': butanta_polygon,
    'morumbi': morumbi_polygon,
    'jaguará': jaguara_polygon,
    'vila leopoldina': vila_leopoldina_polygon,
    'jaguaré': jaguare_polygon,
    'rio pequeno': rio_pequeno_polygon,
    'vila sônia': vila_sonia_polygon
}


export const dict_polygon_colors = {
    // Center
    'bela vista': 'blue',
    'consolação': 'blue',
    'santa cecília': 'blue',
    'república': 'blue',
    'cambuci': 'blue',
    'liberdade': 'blue',
    'bom retiro': 'blue',
    'sé': 'blue',
    // North
    'santana': 'red',
    'vila guilherme': 'red',
    'vila maria': 'red',
    'casa verde': 'red',
    'limão': 'red',
    'freguesia do ó': 'red',
    'pirituba': 'red',
    'são domingos': 'red',
    'vila medeiros': 'red',
    'tucuruvi': 'red',
    'mandaqui': 'red',
    'cachoerinha': 'red',
    'brasilândia': 'red',
    'jaraguá': 'red',
    'tremembé': 'red',
    // East
    'pari': 'yellow',
    'brás': 'yellow',
    'belém': 'yellow',
    'mooca': 'yellow',
    'tatuapé': 'yellow',
    'água rasa': 'yellow',
    'vila prudente': 'yellow',
    'cangaiba': 'yellow',
    'penha': 'yellow',
    'vila matilde': 'yellow',
    'carrão': 'yellow',
    'vila formosa': 'yellow',
    'artur alvim': 'yellow',
    'cidade líder': 'yellow',
    'são mateus': 'yellow',
    'vila jacuí': 'yellow',
    'itaquera': 'yellow',
    'são rafael': 'yellow',
    'josé bonifácio': 'yellow',
    'iguatemi': 'yellow',
    'jardim helena': 'yellow',
    'vila curuçá': 'yellow',
    'guaianases': 'yellow',
    'cidade tiradentes': 'yellow',
    // South
    'vila mariana': 'purple',
    'ipiranga': 'purple',
    'saúde': 'purple',
    'sacomã': 'purple',
    'vila andrade': 'purple',
    'santo amaro': 'purple',
    'campo belo': 'purple',
    'jabaquara': 'purple',
    'capão redondo': 'purple',
    'socorro': 'purple',
    'cidade ademar': 'purple',
    // West
    'barra funda': 'green',
    'perdizes': 'green',
    'jardim paulista': 'green',
    'pinheiros': 'green',
    'itaim bibi': 'green',
    'lapa': 'green',
    'alto pinheiros': 'green',
    'butantã': 'green',
    'morumbi': 'green',
    'jaguará': 'green',
    'vila leopoldina': 'green',
    'jaguaré': 'green',
    'rio pequeno': 'green',
    'vila sônia': 'green'
}