import { 
    //Center
    bela_vista_polygon, 
    consolacao_polygon, 
    liberdade_polygon, 
    santa_cecilia_polygon,
    republica_polygon,
    cambuci_polygon,
    bom_retiro_polygon,
    se_polygon,
    barra_funda_polygon,
    // North
    santana_polygon,
    vila_guilherme_polygon,
    vila_maria_polygon,
    casa_verde_polygon,
    limao_polygon,
    freguesia_do_o_polygon,
    pirituba_polygon,
    sao_domingos_polygon,
    vila_medeiros_polygon,
    tucuruvi_polygon,
    mandaqui_polygon,
    cachoerinha_polygon,
    brasilandia_polygon,
    jaragua_polygon,
    tremembe_polygon,
    //East
    pari_polygon,
    bras_polygon,
    belem_polygon,
    mooca_polygon,
    tatuape_polygon,
    agua_rasa_polygon,
    vila_prudente_polygon,
    cangaiba_polygon,
    penha_polygon,
    vila_matilde_polygon,
    carrao_polygon,
    vila_formosa_polygon,
    artur_alvim_polygon,
    cidade_lider_polygon,
  } from '../../maps/sao_paulo_districts'

  
export const dict_polygon_names = {
    // Center
    'bela vista': bela_vista_polygon,
    'consolação': consolacao_polygon,
    'santa cecília': santa_cecilia_polygon,
    'república': republica_polygon,
    'cambuci': cambuci_polygon,
    'liberdade': liberdade_polygon,
    'bom retiro': bom_retiro_polygon,
    'sé': se_polygon,
    'barra funda': barra_funda_polygon,
    // North
    'santana': santana_polygon,
    'vila guilherme': vila_guilherme_polygon,
    'vila maria': vila_maria_polygon,
    'casa verde': casa_verde_polygon,
    'limão': limao_polygon,
    'freguesia do ó': freguesia_do_o_polygon,
    'pirituba': pirituba_polygon,
    'são domingos': sao_domingos_polygon,
    'vila medeiros': vila_medeiros_polygon,
    'tucuruvi': tucuruvi_polygon,
    'mandaqui': mandaqui_polygon,
    'cachoerinha': cachoerinha_polygon,
    'brasilândia': brasilandia_polygon,
    'jaraguá': jaragua_polygon,
    'tremembé': tremembe_polygon,
    //East
    'pari': pari_polygon,
    'brás': bras_polygon,
    'belém': belem_polygon,
    'mooca': mooca_polygon,
    'tatuapé': tatuape_polygon,
    'água rasa': agua_rasa_polygon,
    'vila prudente': vila_prudente_polygon,
    'cangaiba': cangaiba_polygon,
    'penha': penha_polygon,
    'vila matilde': vila_matilde_polygon,
    'carrão': carrao_polygon,
    'vila formosa': vila_formosa_polygon,
    'artur alvim': artur_alvim_polygon,
    'cidade líder': cidade_lider_polygon,
}


export const dict_polygon_colors = {
    // Center
    'bela vista': 'blue',
    'consolação': 'blue',
    'santa cecília': 'blue',
    'república': 'blue',
    'cambuci': 'blue',
    'liberdade': 'blue',
    'bom retiro': 'blue',
    'sé': 'blue',
    'barra funda': 'blue',
     // North
    'santana': 'red',
    'vila guilherme': 'red',
    'vila maria': 'red',
    'casa verde': 'red',
    'limão': 'red',
    'freguesia do ó': 'red',
    'pirituba': 'red',
    'são domingos': 'red',
    'vila medeiros': 'red',
    'tucuruvi': 'red',
    'mandaqui': 'red',
    'cachoerinha': 'red',
    'brasilândia': 'red',
    'jaraguá': 'red',
    'tremembé': 'red',
    // East
    'pari': 'yellow',
    'brás': 'yellow',
    'belém': 'yellow',
    'mooca': 'yellow',
    'tatuapé': 'yellow',
    'água rasa': 'yellow',
    'vila prudente': 'yellow',
    'cangaiba': 'yellow',
    'penha': 'yellow',
    'vila matilde': 'yellow',
    'carrão': 'yellow',
    'vila formosa': 'yellow',
    'artur alvim': 'yellow',
    'cidade líder': 'yellow'
}